create table
  public.carts (
    id bigint generated by default as identity,
    customer text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity,
    name text null,
    cart_id bigint null,
    quantity integer null,
    potion_id bigint not null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id) on delete cascade,
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potion_inventory (id)
  ) tablespace pg_default;
